spring:
  servlet:
    multipart:
      max-file-size: 1024MB # 最大上传单个文件大小：默认1M
      max-request-size: 1024MB # 最大置总上传的数据大小 ：默认10M
aliyun:
  vod:
    keyid: 
    keysecret: 
    templateGroupId:  #转码模板组id
    workflowId:  #工作流id
