spring:
  mail:
    host: smtp.126.com # 此处使用的是126邮箱进行邮件发送
    username: tl2987894459@126.com # 发送邮件的账号（也就是本人账号）
    password: DBKCAMXTVYMIYZNA # 账号秘钥（注意不是密码！该秘钥在开启SMTP服务时会给出。）
    default-encoding: UTF-8
baidu:
  ak: 9asuVmhVZGIX6UgM2GBrOjaz8G5v9pRB