server:
  tomcat:
    max-threads: 10
spring:
  #spring:
  jackson: #返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 43.143.129.182
    port: 6379
    database: 0
#    lettuce:
#      pool:
#        max-active: 20  #最大连接数，负值表示没有限制，默认8
#        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
#        max-idle: 8     #最大空闲连接，默认8
#        min-idle: 0     #最小空闲连接，默认0
    password:
    timeout: 5000

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719  #默认8719，假如被占用了会自动从8719开始依次+1扫描。直至找到未被占用的端口

# 设置日志级别
logging:
  level:
    root: ERROR
    com.tang.newcloud.service.edu.feign.OssFileService: debug

management:
  endpoints:
    web:
      exposure:
        include: '*'


ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000

feign:
  sentinel:
    enabled: true