server:
  tomcat:
    max-threads: 100
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 设置日志级别
logging:
  level:
    root: info
    com.tang.newcloud.service.edu.feign.OssFileService: debug

ribbon:
  ReadTimeout:  5000
  ConnectTimeout: 5000

feign:
  sentinel:
    enabled: true