spring:
  mail:
    host: smtp.126.com
    username: tl2987894459@126.com
    password: IAQOPLMCZJUBUXTS


#阿里云短信
#aliyun:
#  sms:
#    regionId: cn-hangzhou
#    keyId: 你的keyid
#    keySecret: 你的keysecret
#    templateCode: 你的短信模板code
#    signName: 你的短信模板签名