server:
  port: 8150 # 服务端口

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-sms # 服务名
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 # nacos服务地址
        namespace: 767ef991-26ba-4a95-a648-b4fd2bfb882e
  #spring:
  redis:
    host: 43.143.129.182
    port: 6379
    database: 0
    password: 123 #默认为空
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0
    timeout: 5000

#阿里云短信
aliyun:
  sms:
    regionId: cn-hangzhou
    keyId: 你的keyid
    keySecret: 你的keysecret
    templateCode: 你的短信模板code
    signName: 你的短信模板签名