spring:
  profiles:
    active: dev # 环境设置
  rabbitmq:
    virtual-host: newcloud
    host: 43.143.129.182
    username: tanglei
    password: 5201314
aliyun:
  oss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    keyid: 
    keysecret: 
    #bucket可以在控制台创建，也可以使用java代码创建，注意先测试bucket是否已被占用
    bucketname: newcloud-file
management:
  endpoints:
    web:
      exposure:
        include: '*'


